name = "Formine"
description = "A voxel game written in Fortran."
version = "0.3.0"
license = "MPL-2.0"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"
categories = ["game", "engine", "glfw", "opengl", "stb"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

# Windows needs different linking flags.
# STB becomes a blank export of a C file in the graphics folder.
# link = ["glfw3", "opengl32", "luajit-5.1"]

# MacOS needs different link flags.
# link = ["glfw", "luajit-5.1"]

# Everything else (for now)
link = ["glfw", "stb", "luajit-5.1"]

[dependencies]
forthread = { git = "https://github.com/jordan4ibanez/forthread" }
uuid_now = { git = "https://github.com/jordan4ibanez/uuid_now" }
hashmap_f90 = { git = "https://github.com/jordan4ibanez/hashmap_f90" }

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
