name = "Formine"
description = "A test of learning modern fortran through game dev."
version = "0.2.0"
license = "MPL-2.0"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"
categories = ["game", "engine", "glfw", "opengl"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

link = ["glfw", "GL", "stb", "luajit-5.1"]

[dependencies]
# stdlib = "*"
fhash = { git = "https://github.com/LKedward/fhash.git" }

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
