name = "fortran_thing"
version = "0.1.0"
license = "GPLv3"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
