module raw_data_version_info
  use, intrinsic :: iso_c_binding
  implicit none

  !! DO NOT EDIT THIS FILE MANUALLY !!
  !! THIS FILE IS PRODUCED BY MAKE  !!

  integer(c_int), parameter :: FORMINE_VERSION_MAJOR = 0
  integer(c_int), parameter :: FORMINE_VERSION_MINOR = 3
  integer(c_int), parameter :: FORMINE_VERSION_PATCH = 0
end module raw_data_version_info
